### ISSUE TITLE
Chapter01 fails

### ISSUE THREAD

**Issue by DickBaker** [PacktPublishing/Modern-Web-Development-with-ASP.NET-Core-3-Second-Edition#1]
get "ConfigureServices returning an System.IServiceProvider isn't supported." exception error on Chapter01 !

These URLs shows breaking changes in .NET CORE v3.x
https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting
https://stackoverflow.com/questions/58133507/configureservices-returning-a-system-iserviceprovider-isnt-supported

ASP.NET CORE 3.0 was released 2019-09-23 as per https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/
but this Packt title was released 2020-06, so it is obvious that the download code was not tested in interim 9 months or  immediately prior to book release as one might expect for a professional process. Why no checks by the reviewers or the Packt publisher ?

Do the subsequent chapters have the same blight (in which case the whole book is doomed) or is this just an unfortunate bloopa trying to show that other DI frameworks (Autofac in this case) could be used ?

Unimpressed alas !

**Comment by rjperes** [comment]
Hi. This chapter was written almost two years ago. Yes, this change in 3.1 went unnoticed, both to me and the tech reviewers. I do think that the rest of the code does not suffer from this kind of problems. Thanks for your contribution.
